---
repo_url: https://github.com/Projetos-de-Extensao/PFE_25.2_8002_III
site_author: João Márcio Prado Silva, Nicholas Borges de Vasconcelos, Victor Robson, Matheus pinguim
site_name: Grupo III - Projeto Portal Monitor
site_url: https://projetos-de-extensao.github.io/PFE_25.2_8002_III/
copyright: Copyright ©️ 2025, João Márcio Prado Silva, Nicholas Borges de Vasconcelos, Victor Robson, Matheus pinguim / 2025, João Márcio Prado Silva, Nicholas Borges de Vasconcelos, Victor Robson, Matheus pinguim
docs_dir: docs
site_dir: site

extra_css:
  - css/extra.css

markdown_extensions:
  # Tooltips
  - abbr
  # Admonitions
  - admonition
  # Annotations, Buttons, Grids, Icons & Emojis, Images, Tooltips
  - attr_list
  # Footnotes
  - footnotes
  # Annotations, Grids, Images
  - md_in_html
  # Images
  - pymdownx.blocks.caption
  # Formatting
  - pymdownx.caret
  # Formatting
  - pymdownx.critic
  # Admonitions
  - pymdownx.details
  # Icons & Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ''
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
  # Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # Code Blocks
  - pymdownx.inlinehilite
  # Formatting
  - pymdownx.keys
  # Formatting
  - pymdownx.mark
  # Code Blocks, Tooltips
  - pymdownx.snippets
  # Admonitions, Annotations, Code Blocks, Content Tabs
  - pymdownx.superfences
  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Lists
  - pymdownx.tasklist:
      custom_checkbox: true
  # Formatting
  - pymdownx.tilde
  # Data Tables
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      theme:
        light: catppuccin/latte
        dark: catppuccin/mocha
  - minify:
      minify_html: true

theme:
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    logo: simple/React
    favicon: simple/react
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: green   # Base color, will be overridden by extra.css
      accent: amber    # Base color, will be overridden by extra.css
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green   # Base color, will be overridden by extra.css
      accent: amber    # Base color, will be overridden by extra.css
      toggle:
        icon: material/weather-night
        name: Switch to light mode

#nav: 
 # - Home: index.md
  #- Disciplina:
   #   -  Aulas: Disciplina/Aulas.md
    #  -  Github: github.md
     # -  Mkdocs: mkdocs.md
      #-  CodeSpace: Codespace.md 
  #- React: 
   #   -  Introdução: React/01_Intro.md
    #  -  Componentes: React/Componentes.md
     # -  Hooks: React/Hooks.md
      #-  Context API: React/ContextAPI.md
      #-  React Router: React/ReactRouter.md
      #-  Redux: React/Redux.md